[tool]
[tool.poetry]
authors = ["João Denilson <denilsonsantos021@gmail.com>"]
name = ""
python = "^3.7"
version = "1.0.0"
[tool.poetry.dependencies]
matplotlib = "*"
minisom = "*"
numpy = "*"
python = "*"
